# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

# The Default Profile
[profile.default]
# Sets the concrete solc version to use
# This overrides the `auto_detect_solc` value
solc_version = '0.8.10'
auto_detect_solc = false
# Increase optimizer_runs
optimizer = true
optimizer_runs = 200

out = 'artifacts_foundry'
cache_path = 'cache_foundry'


[fuzz]
runs = 2048
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 2048

[doc]
out = 'docs'
title = 'crossbell-bridge'
ignore = ['contracts/upgradeability/*.sol','contracts/token/*.sol','contracts/*.sol']
