name: checks

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn
      - name: Run lints
        run: yarn lint

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install Dependencies
        run: yarn
      - name: Update Modules
        run: yarn sync
      - name: Run Tests
        run: FOUNDRY_PROFILE=ci yarn test

  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Disable foundry
        run: rm foundry.toml
      - uses: crytic/slither-action@v0.2.0
        with:
          node-version: 14
          fail-on: none
          slither-config: slither.config.json
